export const ADMIN_ROUTER = "/admin"
export const REGISTRETION_ROUTER = "/registretion"
export const LOGIN_ROUTER = "/login"
export const SHOP_ROUTER = "/"
export const BASKET_ROUTER = "/basket"
export const DEVICE_ROUTER = "/device"